import express from 'express';
import dotenv from 'dotenv';

dotenv.config();

const app = express();
const port = process.env.PORT

const quotes = [
{ id: 1, quote: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
{ id: 2, quote: "Life is what happens when you're busy making other plans.", author: "John Lennon" },
{ id: 3, quote: "In the end, we will remember not the words of our enemies, but the silence of our friends.", author: "Martin Luther King Jr." },
{ id: 4, quote: "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.", author: "Ralph Waldo Emerson" },
{ id: 5, quote: "It is not length of life, but depth of life.", author: "Ralph Waldo Emerson" },
{ id: 6, quote: "Do not go where the path may lead, go instead where there is no path and leave a trail.", author: "Ralph Waldo Emerson" },
{ id: 7, quote: "What lies behind us and what lies before us are tiny matters compared to what lies within us.", author: "Ralph Waldo Emerson" },
{ id: 8, quote: "Be yourself; everyone else is already taken.", author: "Oscar Wilde" },
{ id: 9, quote: "Two things are infinite: the universe and human stupidity; and I'm not sure about the universe.", author: "Albert Einstein" },
{ id: 10, quote: "So many books, so little time.", author: "Frank Zappa" },
{ id: 11, quote: "The truth will set you free, but first it will make you miserable.", author: "James A. Garfield" },
{ id: 12, quote: "To be great is to be misunderstood.", author: "Ralph Waldo Emerson" },
{ id: 13, quote: "I am not afraid of tomorrow, for I have seen yesterday and I love today.", author: "William Allen White" },
{ id: 14, quote: "The best way to predict the future is to create it.", author: "Abraham Lincoln" },
{ id: 15, quote: "A journey of a thousand miles begins with a single step.", author: "Lao Tzu" },
{ id: 16, quote: "That which does not kill us makes us stronger.", author: "Friedrich Nietzsche" },
{ id: 17, quote: "In three words I can sum up everything I've learned about life: it goes on.", author: "Robert Frost" },
{ id: 18, quote: "The only true wisdom is in knowing you know nothing.", author: "Socrates" },
{ id: 19, quote: "Be the change that you wish to see in the world.", author: "Mahatma Gandhi" },
{ id: 20, quote: "It does not matter how slowly you go as long as you do not stop.", author: "Confucius" },
{ id: 21, quote: "I think, therefore I am.", author: "René Descartes" },
{ id: 22, quote: "Do what you can, with what you have, where you are.", author: "Theodore Roosevelt" },
{ id: 23, quote: "You must be the change you wish to see in the world.", author: "Mahatma Gandhi" },
{ id: 24, quote: "Life isn't about finding yourself. Life is about creating yourself.", author: "George Bernard Shaw" },
{ id: 25, quote: "Happiness depends upon ourselves.", author: "Aristotle" },
{ id: 26, quote: "The only thing we have to fear is fear itself.", author: "Franklin D. Roosevelt" },
{ id: 27, quote: "Do not dwell in the past, do not dream of the future, concentrate the mind on the present moment.", author: "Buddha" },
{ id: 28, quote: "Success is not final, failure is not fatal: It is the courage to continue that counts.", author: "Winston Churchill" },
{ id: 29, quote: "Hardships often prepare ordinary people for an extraordinary destiny.", author: "C.S. Lewis" },
{ id: 30, quote: "You miss 100% of the shots you don't take.", author: "Wayne Gretzky" },
{ id: 31, quote: "The mind is everything. What you think you become.", author: "Buddha" },
{ id: 32, quote: "An unexamined life is not worth living.", author: "Socrates" },
{ id: 33, quote: "Your time is limited, so don't waste it living someone else's life.", author: "Steve Jobs" },
{ id: 34, quote: "The greatest glory in living lies not in never falling, but in rising every time we fall.", author: "Nelson Mandela" },
{ id: 35, quote: "The purpose of our lives is to be happy.", author: "Dalai Lama" },
{ id: 36, quote: "Get busy living or get busy dying.", author: "Stephen King" },
{ id: 37, quote: "You have enemies? Good. That means you've stood up for something, sometime in your life.", author: "Winston Churchill" },
{ id: 38, quote: "To live is the rarest thing in the world. Most people exist, that is all.", author: "Oscar Wilde" },
{ id: 39, quote: "Life is really simple, but we insist on making it complicated.", author: "Confucius" },
{ id: 40, quote: "Everything you can imagine is real.", author: "Pablo Picasso" },
{ id: 41, quote: "If you can dream it, you can do it.", author: "Walt Disney" },
{ id: 42, quote: "I alone cannot change the world, but I can cast a stone across the waters to create many ripples.", author: "Mother Teresa" },
{ id: 43, quote: "Believe you can and you're halfway there.", author: "Theodore Roosevelt" },
{ id: 44, quote: "It always seems impossible until it's done.", author: "Nelson Mandela" },
{ id: 45, quote: "Doubt kills more dreams than failure ever will.", author: "Suzy Kassem" },
{ id: 46, quote: "What we think, we become.", author: "Buddha" },
{ id: 47, quote: "The best revenge is massive success.", author: "Frank Sinatra" },
{ id: 48, quote: "Life is short, and it's up to you to make it sweet.", author: "Sarah Louise Delany" },
{ id: 49, quote: "Success usually comes to those who are too busy to be looking for it.", author: "Henry David Thoreau" },
{ id: 50, quote: "Life itself is the most wonderful fairy tale.", author: "Hans Christian Andersen" },
{ id: 51, quote: "A person who never made a mistake never tried anything new.", author: "Albert Einstein" },
{ id: 52, quote: "Keep your face always toward the sunshine—and shadows will fall behind you.", author: "Walt Whitman" },
{ id: 53, quote: "To succeed in life, you need three things: a wishbone, a backbone and a funny bone.", author: "Reba McEntire" },
{ id: 54, quote: "If you are not willing to risk the usual, you will have to settle for the ordinary.", author: "Jim Rohn" },
{ id: 55, quote: "Success is how high you bounce when you hit bottom.", author: "George S. Patton" },
{ id: 56, quote: "Tell me and I forget. Teach me and I remember. Involve me and I learn.", author: "Benjamin Franklin" },
{ id: 57, quote: "Everything has beauty, but not everyone sees it.", author: "Confucius" },
{ id: 58, quote: "Innovation distinguishes between a leader and a follower.", author: "Steve Jobs" },
{ id: 59, quote: "Opportunities don't happen. You create them.", author: "Chris Grosser" },
{ id: 60, quote: "Dream big and dare to fail.", author: "Norman Vaughan" },
{ id: 61, quote: "You need to be prepared for failure before you can take the risks for success.", author: "Nikki Giovanni" },
{ id: 62, quote: "Act as if what you do makes a difference. It does.", author: "William James" },
{ id: 63, quote: "Success is walking from failure to failure with no loss of enthusiasm.", author: "Winston S. Churchill" },
{ id: 64, quote: "Everything you've ever wanted is on the other side of fear.", author: "George Addair" },
{ id: 65, quote: "Success isn't just about what you accomplish in your life. It's about what you inspire others to do.", author: "Unknown" },
{ id: 66, quote: "You are enough just as you are.", author: "Megan Markle" },
{ id: 67, quote: "The only person you are destined to become is the person you decide to be.", author: "Ralph Waldo Emerson" },
{ id: 68, quote: "Success is the sum of small efforts repeated day in and day out.", author: "Robert Collier" },
{ id: 69, quote: "Don’t watch the clock; do what it does. Keep going.", author: "Sam Levenson" },
{ id: 70, quote: "What we achieve inwardly will change outer reality.", author: "Plutarch" },
{ id: 71, quote: "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.", author: "Christian D. Larson" },
{ id: 72, quote: "Progress is impossible without change, and those who cannot change their minds cannot change anything.", author: "George Bernard Shaw" },
{ id: 73, quote: "The greatest glory in living lies not in never falling, but in rising every time we fall.", author: "Nelson Mandela" },
{ id: 74, quote: "Life is 10% what happens to us and 90% how we react to it.", author: "Charles R. Swindoll" },
{ id: 75, quote: "Failure is simply the opportunity to begin again, this time more intelligently.", author: "Henry Ford" },
{ id: 76, quote: "What you get by achieving your goals is not as important as what you become by achieving your goals.", author: "Zig Ziglar" },
{ id: 77, quote: "I find that the harder I work, the more luck I seem to have.", author: "Thomas Jefferson" },
{ id: 78, quote: "The way to get started is to quit talking and begin doing.", author: "Walt Disney" },
{ id: 79, quote: "Life is either a daring adventure or nothing at all.", author: "Helen Keller" },
{ id: 80, quote: "Strive not to be a success, but rather to be of value.", author: "Albert Einstein" },
{ id: 81, quote: "Our lives begin to end the day we become silent about things that matter.", author: "Martin Luther King Jr." },
{ id: 82, quote: "Success is how high you bounce when you hit bottom.", author: "General George Patton" },
{ id: 83, quote: "The only limit to our realization of tomorrow will be our doubts of today.", author: "Franklin D. Roosevelt" },
{ id: 84, quote: "You must expect great things of yourself before you can do them.", author: "Michael Jordan" },
{ id: 85, quote: "Your time is limited, so don’t waste it living someone else’s life.", author: "Steve Jobs" },
{ id: 86, quote: "Not how long, but how well you have lived is the main thing.", author: "Seneca" },
{ id: 87, quote: "The best way to cheer yourself is to try to cheer someone else up.", author: "Mark Twain" },
{ id: 88, quote: "If you want to lift yourself up, lift up someone else.", author: "Booker T. Washington" },
{ id: 89, quote: "The only way to achieve the impossible is to believe it is possible.", author: "Charles Kingsleigh" },
{ id: 90, quote: "Success is not how high you have climbed, but how you make a positive difference to the world.", author: "Roy T. Bennett" },
{ id: 91, quote: "Everything you can imagine is real.", author: "Pablo Picasso" },
{ id: 92, quote: "What counts in life is not the mere fact that we have lived. It is what difference we have made to the lives of others that will determine the significance of the life we lead.", author: "Nelson Mandela" },
{ id: 93, quote: "Opportunities multiply as they are seized.", author: "Sun Tzu" },
{ id: 94, quote: "Success is to be measured not so much by the position that one has reached in life as by the obstacles which he has overcome.", author: "Booker T. Washington" },
{ id: 95, quote: "Happiness is not a goal; it is a by-product.", author: "Eleanor Roosevelt" },
{ id: 96, quote: "The best dreams happen when you’re awake.", author: "Cherie Gilderbloom" },
{ id: 97, quote: "You are never too old to set another goal or to dream a new dream.", author: "C.S. Lewis" },
{ id: 98, quote: "Success is the ability to go from one failure to another with no loss of enthusiasm.", author: "Winston Churchill" },
{ id: 99, quote: "Life is what we make it, always has been, always will be.", author: "Grandma Moses" },
{ id: 100, quote: "Limit your 'always' and your 'nevers'.", author: "Amy Poehler" },
{ id: 101, quote: "The best way to predict the future is to create it.", author: "Abraham Lincoln" },
{ id: 102, quote: "In the end, we will remember not the words of our enemies, but the silence of our friends.", author: "Martin Luther King Jr." },
{ id: 103, quote: "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.", author: "Ralph Waldo Emerson" },
{ id: 104, quote: "It is not length of life, but depth of life.", author: "Ralph Waldo Emerson" },
{ id: 105, quote: "Do not go where the path may lead, go instead where there is no path and leave a trail.", author: "Ralph Waldo Emerson" },
{ id: 106, quote: "What lies behind us and what lies before us are tiny matters compared to what lies within us.", author: "Ralph Waldo Emerson" },
{ id: 107, quote: "Be yourself; everyone else is already taken.", author: "Oscar Wilde" },
{ id: 108, quote: "Two things are infinite: the universe and human stupidity; and I'm not sure about the universe.", author: "Albert Einstein" },
{ id: 109, quote: "So many books, so little time.", author: "Frank Zappa" },
{ id: 110, quote: "The truth will set you free, but first it will make you miserable.", author: "James A. Garfield" },
{ id: 111, quote: "To be great is to be misunderstood.", author: "Ralph Waldo Emerson" },
{ id: 112, quote: "I am not afraid of tomorrow, for I have seen yesterday and I love today.", author: "William Allen White" },
{ id: 113, quote: "The best way to predict the future is to create it.", author: "Abraham Lincoln" },
{ id: 114, quote: "A journey of a thousand miles begins with a single step.", author: "Lao Tzu" },
{ id: 115, quote: "That which does not kill us makes us stronger.", author: "Friedrich Nietzsche" },
{ id: 116, quote: "In three words I can sum up everything I've learned about life: it goes on.", author: "Robert Frost" },
{ id: 117, quote: "The only true wisdom is in knowing you know nothing.", author: "Socrates" },
{ id: 118, quote: "Be the change that you wish to see in the world.", author: "Mahatma Gandhi" },
{ id: 119, quote: "It does not matter how slowly you go as long as you do not stop.", author: "Confucius" },
{ id: 120, quote: "I think, therefore I am.", author: "René Descartes" },
{ id: 121, quote: "Do what you can, with what you have, where you are.", author: "Theodore Roosevelt" },
{ id: 122, quote: "You must be the change you wish to see in the world.", author: "Mahatma Gandhi" },
{ id: 123, quote: "Life isn't about finding yourself. Life is about creating yourself.", author: "George Bernard Shaw" },
{ id: 124, quote: "Happiness depends upon ourselves.", author: "Aristotle" },
{ id: 125, quote: "The only thing we have to fear is fear itself.", author: "Franklin D. Roosevelt" },
{ id: 126, quote: "Do not dwell in the past, do not dream of the future, concentrate the mind on the present moment.", author: "Buddha" },
{ id: 127, quote: "Success is not final, failure is not fatal: It is the courage to continue that counts.", author: "Winston Churchill" },
{ id: 128, quote: "Hardships often prepare ordinary people for an extraordinary destiny.", author: "C.S. Lewis" },
{ id: 129, quote: "You miss 100% of the shots you don't take.", author: "Wayne Gretzky" },
{ id: 130, quote: "The mind is everything. What you think you become.", author: "Buddha" },
{ id: 131, quote: "An unexamined life is not worth living.", author: "Socrates" },
{ id: 132, quote: "Your time is limited, so don't waste it living someone else's life.", author: "Steve Jobs" },
{ id: 133, quote: "The greatest glory in living lies not in never falling, but in rising every time we fall.", author: "Nelson Mandela" },
{ id: 134, quote: "The purpose of our lives is to be happy.", author: "Dalai Lama" },
{ id: 135, quote: "Get busy living or get busy dying.", author: "Stephen King" },
{ id: 136, quote: "You have enemies? Good. That means you've stood up for something, sometime in your life.", author: "Winston Churchill" },
{ id: 137, quote: "To live is the rarest thing in the world. Most people exist, that is all.", author: "Oscar Wilde" },
{ id: 138, quote: "Life is really simple, but we insist on making it complicated.", author: "Confucius" },
{ id: 139, quote: "Everything you can imagine is real.", author: "Pablo Picasso" },
{ id: 140, quote: "If you can dream it, you can do it.", author: "Walt Disney" },
{ id: 141, quote: "I alone cannot change the world, but I can cast a stone across the waters to create many ripples.", author: "Mother Teresa" },
{ id: 142, quote: "Believe you can and you're halfway there.", author: "Theodore Roosevelt" },
{ id: 143, quote: "It always seems impossible until it's done.", author: "Nelson Mandela" },
{ id: 144, quote: "Success is not how high you have climbed, but how you make a positive difference to the world.", author: "Albert Einstein" },
{ id: 145, quote: "You become what you believe.", author: "Steve Jobs" },
{ id: 146, quote: "Do not be embarrassed by your failures, learn from them and start again.", author: "Mark Twain" },
{ id: 147, quote: "Don’t count the days, make the days count.", author: "Rumi" },
{ id: 148, quote: "You can’t go back and change the beginning, but you can start where you are and change the ending.", author: "Oprah Winfrey" },
{ id: 149, quote: "Push yourself, because no one else is going to do it for you.", author: "Leo Tolstoy" },
{ id: 150, quote: "Start where you are. Use what you have. Do what you can.", author: "Brene Brown" },
{ id: 151, quote: "I am not a product of my circumstances. I am a product of my decisions.", author: "Tony Robbins" },
{ id: 152, quote: "Don't let yesterday take up too much of today.", author: "Jim Rohn" },
{ id: 153, quote: "If you want to achieve greatness stop asking for permission.", author: "Napoleon Hill" },
{ id: 154, quote: "A goal without a plan is just a wish.", author: "Helen Keller" },
{ id: 155, quote: "What you do today can improve all your tomorrows.", author: "Zig Ziglar" },
{ id: 156, quote: "Don’t wait for opportunity. Create it.", author: "Brian Tracy" },
{ id: 157, quote: "Keep your eyes on the stars and your feet on the ground.", author: "Elon Musk" },
{ id: 158, quote: "Go the extra mile. It's never crowded.", author: "J.K. Rowling" },
{ id: 159, quote: "Great minds discuss ideas; average minds discuss events; small minds discuss people.", author: "Marie Curie" },
{ id: 160, quote: "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart.", author: "Isaac Newton" },
{ id: 161, quote: "If you want something you've never had, you must be willing to do something you've never done.", author: "Carl Jung" },
{ id: 162, quote: "Everything you’ve ever wanted is on the other side of fear.", author: "Stephen Hawking" },
{ id: 163, quote: "If opportunity doesn’t knock, build a door.", author: "Niccolò Machiavelli" },
{ id: 164, quote: "Success is not how high you have climbed, but how you make a positive difference to the world.", author: "Sun Tzu" },
{ id: 165, quote: "You become what you believe.", author: "Maya Angelou" },
{ id: 166, quote: "Do not be embarrassed by your failures, learn from them and start again.", author: "Dale Carnegie" },
{ id: 167, quote: "Don’t count the days, make the days count.", author: "Paulo Coelho" },
{ id: 168, quote: "You can’t go back and change the beginning, but you can start where you are and change the ending.", author: "Charles Darwin" },
{ id: 169, quote: "Push yourself, because no one else is going to do it for you.", author: "Walt Whitman" },
{ id: 170, quote: "Start where you are. Use what you have. Do what you can.", author: "Bruce Lee" },
{ id: 171, quote: "I am not a product of my circumstances. I am a product of my decisions.", author: "Confucius" },
{ id: 172, quote: "Don't let yesterday take up too much of today.", author: "Plato" },
{ id: 173, quote: "If you want to achieve greatness stop asking for permission.", author: "Aristotle" },
{ id: 174, quote: "A goal without a plan is just a wish.", author: "Albert Einstein" },
{ id: 175, quote: "What you do today can improve all your tomorrows.", author: "Steve Jobs" },
{ id: 176, quote: "A goal without a plan is just a wish.", author: "Antoine de Saint-Exupéry" },
{ id: 177, quote: "Don’t count the days, make the days count.", author: "Muhammad Ali" },
{ id: 178, quote: "Turn your wounds into wisdom.", author: "Oprah Winfrey" },
{ id: 179, quote: "If opportunity doesn’t knock, build a door.", author: "Milton Berle" },
{ id: 180, quote: "The only journey is the one within.", author: "Rainer Maria Rilke" },
{ id: 181, quote: "Do not wait to strike till the iron is hot; but make it hot by striking.", author: "William Butler Yeats" },
{ id: 182, quote: "Either you run the day, or the day runs you.", author: "Jim Rohn" },
{ id: 183, quote: "Be led by the dreams in your heart.", author: "Roy T. Bennett" },
{ id: 184, quote: "Great minds discuss ideas; average minds discuss events; small minds discuss people.", author: "Eleanor Roosevelt" },
{ id: 185, quote: "Work hard in silence, let success make the noise.", author: "Frank Ocean" },
{ id: 186, quote: "You are never too old to set another goal or to dream a new dream.", author: "C.S. Lewis" },
{ id: 187, quote: "Life is what happens when you're busy making other plans.", author: "John Lennon" },
{ id: 188, quote: "We may encounter many defeats, but we must not be defeated.", author: "Maya Angelou" },
{ id: 189, quote: "Success usually comes to those who are too busy to be looking for it.", author: "Henry David Thoreau" },
{ id: 190, quote: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
{ id: 191, quote: "You don’t have to be great to start, but you have to start to be great.", author: "Zig Ziglar" },
{ id: 192, quote: "Success is not in what you have, but who you are.", author: "Bo Bennett" },
{ id: 193, quote: "I find that the harder I work, the more luck I seem to have.", author: "Thomas Jefferson" },
{ id: 194, quote: "Everything you've ever wanted is on the other side of fear.", author: "George Addair" },
{ id: 195, quote: "The way to get started is to quit talking and begin doing.", author: "Walt Disney" },
{ id: 196, quote: "Do one thing every day that scares you.", author: "Eleanor Roosevelt" },
{ id: 197, quote: "It does not matter how slowly you go as long as you do not stop.", author: "Confucius" },
{ id: 198, quote: "You only live once, but if you do it right, once is enough.", author: "Mae West" },
{ id: 199, quote: "Believe you can and you're halfway there.", author: "Theodore Roosevelt" },
{ id: 200, quote: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt" },
{ id: 201, quote: "You don’t have to be great to start, but you have to start to be great.", author: "Zig Ziglar" },
{ id: 202, quote: "Small deeds done are better than great deeds planned.", author: "Peter Marshall" },
{ id: 203, quote: "Don’t let yesterday take up too much of today.", author: "Will Rogers" },
{ id: 204, quote: "Success is the progressive realization of a worthy goal or ideal.", author: "Earl Nightingale" },
{ id: 205, quote: "Your limitation—it’s only your imagination.", author: "Unknown" },
{ id: 206, quote: "Sometimes we’re tested not to show our weaknesses, but to discover our strengths.", author: "Unknown" },
{ id: 207, quote: "The harder you work for something, the greater you’ll feel when you achieve it.", author: "Unknown" },
{ id: 208, quote: "The key to success is to focus on goals, not obstacles.", author: "Unknown" },
{ id: 209, quote: "Dream it. Wish it. Do it.", author: "Unknown" },
{ id: 210, quote: "Don’t stop when you’re tired. Stop when you’re done.", author: "Marilyn Monroe" },
{ id: 211, quote: "Difficult roads often lead to beautiful destinations.", author: "Zig Ziglar" },
{ id: 212, quote: "Work until your idols become your rivals.", author: "Drake" },
{ id: 213, quote: "If you’re going through hell, keep going.", author: "Winston Churchill" },
{ id: 214, quote: "What you get by achieving your goals is not as important as what you become by achieving your goals.", author: "Zig Ziglar" },
{ id: 215, quote: "Wake up with determination. Go to bed with satisfaction.", author: "Unknown" },
{ id: 216, quote: "Success is not for the chosen few, but for the few who choose it.", author: "Unknown" },
{ id: 217, quote: "Discipline is doing what needs to be done, even if you don’t want to do it.", author: "Unknown" },
{ id: 218, quote: "The expert in anything was once a beginner.", author: "Helen Hayes" },
{ id: 219, quote: "Perseverance is not a long race; it is many short races one after the other.", author: "Walter Elliot" },
{ id: 220, quote: "Success doesn’t come from what you do occasionally. It comes from what you do consistently.", author: "Marie Forleo" },
{ id: 221, quote: "You didn’t come this far to only come this far.", author: "Tom Brady" },
{ id: 222, quote: "There is no substitute for hard work.", author: "Thomas Edison" },
{ id: 223, quote: "It’s not about perfect. It’s about effort.", author: "Jillian Michaels" },
{ id: 224, quote: "Every accomplishment starts with the decision to try.", author: "John F. Kennedy" },
{ id: 225, quote: "Success is a series of small wins.", author: "Unknown" },
{ id: 226, quote: "The best preparation for tomorrow is doing your best today.", author: "H. Jackson Brown Jr." },
{ id: 227, quote: "You are capable of amazing things.", author: "Unknown" },
{ id: 228, quote: "The pain you feel today will be the strength you feel tomorrow.", author: "Unknown" },
{ id: 229, quote: "Success is liking yourself, liking what you do, and liking how you do it.", author: "Maya Angelou" },
{ id: 230, quote: "Don’t downgrade your dream just to fit your reality.", author: "Unknown" },
{ id: 231, quote: "A river cuts through rock not because of its power, but because of its persistence.", author: "James N. Watkins" },
{ id: 232, quote: "It always seems impossible until it’s done.", author: "Nelson Mandela" },
{ id: 233, quote: "Success doesn’t rush. The greatest reward is the journey.", author: "Unknown" },
{ id: 234, quote: "Start small. Think big. Act now.", author: "Robin Sharma" },
{ id: 235, quote: "Courage doesn’t always roar. Sometimes it’s the quiet voice at the end of the day saying, ‘I will try again tomorrow.’", author: "Mary Anne Radmacher" },
{ id: 236, quote: "Do not let what you cannot do interfere with what you can do.", author: "John Wooden" },
{ id: 237, quote: "Don’t wait for opportunity. Create it.", author: "George Bernard Shaw" },
{ id: 238, quote: "The difference between ordinary and extraordinary is that little extra.", author: "Jimmy Johnson" },
{ id: 239, quote: "Success means doing the best we can with what we have.", author: "Zig Ziglar" },
{ id: 240, quote: "You don’t need to see the whole staircase, just take the first step.", author: "Martin Luther King Jr." },
{ id: 241, quote: "Work hard, be kind, and amazing things will happen.", author: "Conan O'Brien" },
{ id: 242, quote: "There are no shortcuts to any place worth going.", author: "Beverly Sills" },
{ id: 243, quote: "The only way to achieve the impossible is to believe it is possible.", author: "Charles Kingsleigh" },
{ id: 244, quote: "Success is a state of mind. If you want success, start thinking of yourself as a success.", author: "Joyce Brothers" },
{ id: 245, quote: "Failure will never overtake me if my determination to succeed is strong enough.", author: "Og Mandino" },
{ id: 246, quote: "Success is when the checks don’t bounce.", author: "Andy Warhol" },
{ id: 247, quote: "You only fail when you stop trying.", author: "Albert Einstein" },
{ id: 248, quote: "The best way out is always through.", author: "Robert Frost" },
{ id: 249, quote: "You don’t have to see the whole path. Just take the first step.", author: "Martin Luther King Jr." },
{ id: 250, quote: "Winners are not afraid of losing. But losers are.", author: "Robert Kiyosaki" },
{ id: 251, quote: "Success is not the key to happiness. Happiness is the key to success.", author: "Albert Schweitzer" },
{ id: 252, quote: "Your limitation—it's only your imagination.", author: "Unknown" },
{ id: 253, quote: "Push yourself, because no one else is going to do it for you.", author: "Unknown" },
{ id: 254, quote: "Great things never come from comfort zones.", author: "Neil Strauss" },
{ id: 255, quote: "Dream it. Wish it. Do it.", author: "Unknown" },
{ id: 256, quote: "Success doesn’t just find you. You have to go out and get it.", author: "Unknown" },
{ id: 257, quote: "The harder you work for something, the greater you’ll feel when you achieve it.", author: "Unknown" },
{ id: 258, quote: "Dream bigger. Do bigger.", author: "Unknown" },
{ id: 259, quote: "Don't stop when you're tired. Stop when you're done.", author: "Unknown" },
{ id: 260, quote: "Wake up with determination. Go to bed with satisfaction.", author: "Unknown" },
{ id: 261, quote: "Little things make big days.", author: "Unknown" },
{ id: 262, quote: "It’s going to be hard, but hard does not mean impossible.", author: "Unknown" },
{ id: 263, quote: "Don’t wait for opportunity. Create it.", author: "Unknown" },
{ id: 264, quote: "Sometimes we’re tested not to show our weaknesses, but to discover our strengths.", author: "Unknown" },
{ id: 265, quote: "The key to success is to focus on goals, not obstacles.", author: "Unknown" },
{ id: 266, quote: "Dream it. Believe it. Build it.", author: "Unknown" },
{ id: 267, quote: "It’s never too late to be what you might have been.", author: "George Eliot" },
{ id: 268, quote: "You don’t have to be great to start, but you have to start to be great.", author: "Zig Ziglar" },
{ id: 269, quote: "The secret to getting ahead is getting started.", author: "Mark Twain" },
{ id: 270, quote: "Go the extra mile. It's never crowded.", author: "Wayne Dyer" },
{ id: 271, quote: "Everything you can imagine is real.", author: "Pablo Picasso" },
{ id: 272, quote: "It always seems impossible until it's done.", author: "Nelson Mandela" },
{ id: 273, quote: "What we think, we become.", author: "Buddha" },
{ id: 274, quote: "If you want to fly, you have to give up the things that weigh you down.", author: "Toni Morrison" },
{ id: 275, quote: "Success is not final, failure is not fatal: It is the courage to continue that counts.", author: "Winston Churchill" },
{ id: 276, quote: "The harder you work, the luckier you get.", author: "Gary Player" },
{ id: 277, quote: "Your time is limited, so don’t waste it living someone else’s life.", author: "Steve Jobs" },
{ id: 278, quote: "You can never cross the ocean until you have the courage to lose sight of the shore.", author: "Christopher Columbus" },
{ id: 279, quote: "The best time to plant a tree was 20 years ago. The second best time is now.", author: "Chinese Proverb" },
{ id: 280, quote: "If you can dream it, you can do it.", author: "Walt Disney" },
{ id: 281, quote: "Your life does not get better by chance, it gets better by change.", author: "Jim Rohn" },
{ id: 282, quote: "Live as if you were to die tomorrow. Learn as if you were to live forever.", author: "Mahatma Gandhi" },
{ id: 283, quote: "If you want to achieve greatness stop asking for permission.", author: "Unknown" },
{ id: 284, quote: "Everything you've ever wanted is on the other side of fear.", author: "George Addair" },
{ id: 285, quote: "Opportunities don't happen, you create them.", author: "Chris Grosser" },
{ id: 286, quote: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt" },
{ id: 287, quote: "Don’t watch the clock; do what it does. Keep going.", author: "Sam Levenson" },
{ id: 288, quote: "Success is not how high you have climbed, but how you make a positive difference to the world.", author: "Roy T. Bennett" },
{ id: 289, quote: "Happiness is not something ready-made. It comes from your own actions.", author: "Dalai Lama" },
{ id: 290, quote: "Success is not in what you have, but who you are.", author: "Bo Bennett" },
{ id: 291, quote: "The only limit to our realization of tomorrow is our doubts of today.", author: "Franklin D. Roosevelt" },
{ id: 292, quote: "Start where you are. Use what you have. Do what you can.", author: "Arthur Ashe" },
{ id: 293, quote: "You are never too old to set another goal or to dream a new dream.", author: "C.S. Lewis" },
{ id: 294, quote: "In order to succeed, we must first believe that we can.", author: "Nikos Kazantzakis" },
{ id: 295, quote: "Success doesn't come from what you do occasionally, it comes from what you do consistently.", author: "Marie Forleo" },
{ id: 296, quote: "The best way to predict the future is to create it.", author: "Abraham Lincoln" },
{ id: 297, quote: "Life is 10% what happens to us and 90% how we react to it.", author: "Charles R. Swindoll" },
{ id: 298, quote: "Hardships often prepare ordinary people for an extraordinary destiny.", author: "C.S. Lewis" },
{ id: 299, quote: "Success is a journey, not a destination.", author: "Ben Sweetland" },
{ id: 300, quote: "Life isn’t about finding yourself. It’s about creating yourself.", author: "George Bernard Shaw" },
{ id: 301, quote: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
{ id: 302, quote: "The best revenge is massive success.", author: "Frank Sinatra" },
{ id: 303, quote: "Success usually comes to those who are too busy to be looking for it.", author: "Henry David Thoreau" },
{ id: 304, quote: "Don't watch the clock; do what it does. Keep going.", author: "Sam Levenson" },
{ id: 305, quote: "You don't have to be great to start, but you have to start to be great.", author: "Zig Ziglar" },
{ id: 306, quote: "It does not matter how slowly you go as long as you do not stop.", author: "Confucius" },
{ id: 307, quote: "Act as if what you do makes a difference. It does.", author: "William James" },
{ id: 308, quote: "Success is not the key to happiness. Happiness is the key to success.", author: "Albert Schweitzer" },
{ id: 309, quote: "Don't be afraid to give up the good to go for the great.", author: "John D. Rockefeller" },
{ id: 310, quote: "Success is not in what you have, but who you are.", author: "Bo Bennett" },
{ id: 311, quote: "Success is to be measured not so much by the position that one has reached in life as by the obstacles which he has overcome.", author: "Booker T. Washington" },
{ id: 312, quote: "Success is not how high you have climbed, but how you make a positive difference to the world.", author: "Roy T. Bennett" },
{ id: 313, quote: "If you're going through hell, keep going.", author: "Winston Churchill" },
{ id: 314, quote: "The only limit to our realization of tomorrow is our doubts of today.", author: "Franklin D. Roosevelt" },
{ id: 315, quote: "The harder you work for something, the greater you’ll feel when you achieve it.", author: "Unknown" },
{ id: 316, quote: "You miss 100% of the shots you don't take.", author: "Wayne Gretzky" },
{ id: 317, quote: "Believe you can and you're halfway there.", author: "Theodore Roosevelt" },
{ id: 318, quote: "We may encounter many defeats, but we must not be defeated.", author: "Maya Angelou" },
{ id: 319, quote: "It always seems impossible until it's done.", author: "Nelson Mandela" },
{ id: 320, quote: "The best way to predict the future is to create it.", author: "Abraham Lincoln" },
{ id: 321, quote: "Dream big and dare to fail.", author: "Norman Vaughan" },
{ id: 322, quote: "The harder you work, the luckier you get.", author: "Gary Player" },
{ id: 323, quote: "Don’t wait for opportunity. Create it.", author: "Unknown" },
{ id: 324, quote: "Everything you’ve ever wanted is on the other side of fear.", author: "George Addair" },
{ id: 325, quote: "Start where you are. Use what you have. Do what you can.", author: "Arthur Ashe" },
{ id: 326, quote: "You are never too old to set another goal or to dream a new dream.", author: "C.S. Lewis" },
{ id: 327, quote: "Success is not the key to happiness. Happiness is the key to success.", author: "Albert Schweitzer" },
{ id: 328, quote: "You can’t cross the sea merely by standing and staring at the water.", author: "Rabindranath Tagore" },
{ id: 329, quote: "If you want to achieve greatness stop asking for permission.", author: "Unknown" },
{ id: 330, quote: "Success doesn’t just find you. You have to go out and get it.", author: "Unknown" },
{ id: 331, quote: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt" },
{ id: 332, quote: "Work hard in silence, let success make the noise.", author: "Frank Ocean" },
{ id: 333, quote: "You are never too old to set another goal or to dream a new dream.", author: "Les Brown" },
{ id: 334, quote: "The road to success and the road to failure are almost exactly the same.", author: "Colin R. Davis" },
{ id: 335, quote: "Don't limit your challenges. Challenge your limits.", author: "Jerry Dunn" },
{ id: 336, quote: "Work hard in silence, let your success be your noise.", author: "Frank Ocean" },
{ id: 337, quote: "Don’t be afraid to give up the good to go for the great.", author: "John D. Rockefeller" },
{ id: 338, quote: "Everything you can imagine is real.", author: "Pablo Picasso" },
{ id: 339, quote: "Dream it. Believe it. Build it.", author: "Unknown" },
{ id: 340, quote: "Success usually comes to those who are too busy to be looking for it.", author: "Henry David Thoreau" },
{ id: 341, quote: "The best revenge is massive success.", author: "Frank Sinatra" },
{ id: 342, quote: "The secret of getting ahead is getting started.", author: "Mark Twain" },
{ id: 343, quote: "Success is not how high you have climbed, but how you make a positive difference to the world.", author: "Roy T. Bennett" },
{ id: 344, quote: "Do what you can with all you have, wherever you are.", author: "Theodore Roosevelt" },
{ id: 345, quote: "The harder you work, the luckier you get.", author: "Gary Player" },
{ id: 346, quote: "Your limitation—it's only your imagination.", author: "Unknown" },
{ id: 347, quote: "Push yourself, because no one else is going to do it for you.", author: "Unknown" },
{ id: 348, quote: "Great things never come from comfort zones.", author: "Neil Strauss" },
{ id: 349, quote: "Dream bigger. Do bigger.", author: "Unknown" },
{ id: 350, quote: "Don’t stop when you’re tired. Stop when you’re done.", author: "Unknown" },
{ id: 351, quote: "Wake up with determination. Go to bed with satisfaction.", author: "Unknown" },
{ id: 352, quote: "Little things make big days.", author: "Unknown" },
{ id: 353, quote: "It’s going to be hard, but hard does not mean impossible.", author: "Unknown" },
{ id: 354, quote: "Don’t wait for opportunity. Create it.", author: "Unknown" },
{ id: 355, quote: "Sometimes we’re tested not to show our weaknesses, but to discover our strengths.", author: "Unknown" },
{ id: 356, quote: "The key to success is to focus on goals, not obstacles.", author: "Unknown" },
{ id: 357, quote: "Dream it. Believe it. Build it.", author: "Unknown" },
{ id: 358, quote: "It’s never too late to be what you might have been.", author: "George Eliot" },
{ id: 359, quote: "You don’t have to be great to start, but you have to start to be great.", author: "Zig Ziglar" },
{ id: 360, quote: "The secret to getting ahead is getting started.", author: "Mark Twain" },
{ id: 361, quote: "Go the extra mile. It's never crowded.", author: "Wayne Dyer" },
{ id: 362, quote: "Everything you can imagine is real.", author: "Pablo Picasso" },
{ id: 363, quote: "It always seems impossible until it's done.", author: "Nelson Mandela" },
{ id: 364, quote: "What we think, we become.", author: "Buddha" },
{ id: 365, quote: "If you want to fly, you have to give up the things that weigh you down.", author: "Toni Morrison" },
{ id: 366, quote: "Success is not final, failure is not fatal: It is the courage to continue that counts.", author: "Winston Churchill" },
{ id: 367, quote: "The harder you work, the luckier you get.", author: "Gary Player" },
{ id: 368, quote: "Your time is limited, so don’t waste it living someone else’s life.", author: "Steve Jobs" },
{ id: 369, quote: "You can never cross the ocean until you have the courage to lose sight of the shore.", author: "Christopher Columbus" },
{ id: 370, quote: "The best time to plant a tree was 20 years ago. The second best time is now.", author: "Chinese Proverb" },
{ id: 371, quote: "If you can dream it, you can do it.", author: "Walt Disney" },
{ id: 372, quote: "Your life does not get better by chance, it gets better by change.", author: "Jim Rohn" },
{ id: 373, quote: "Live as if you were to die tomorrow. Learn as if you were to live forever.", author: "Mahatma Gandhi" },
{ id: 374, quote: "If you want to achieve greatness stop asking for permission.", author: "Unknown" },
{ id: 375, quote: "Everything you've ever wanted is on the other side of fear.", author: "George Addair" },
{ id: 376, quote: "Opportunities don't happen, you create them.", author: "Chris Grosser" },
{ id: 377, quote: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt" },
{ id: 378, quote: "Don’t watch the clock; do what it does. Keep going.", author: "Sam Levenson" },
{ id: 379, quote: "Success is not how high you have climbed, but how you make a positive difference to the world.", author: "Roy T. Bennett" },
{ id: 380, quote: "Happiness is not something ready-made. It comes from your own actions.", author: "Dalai Lama" },
{ id: 381, quote: "Success is not in what you have, but who you are.", author: "Bo Bennett" },
{ id: 382, quote: "Success is not how high you have climbed, but how you make a positive difference to the world.", author: "Roy T. Bennett" },
{ id: 383, quote: "Don’t limit your challenges. Challenge your limits.", author: "Jerry Dunn" },
{ id: 384, quote: "The secret of getting ahead is getting started.", author: "Mark Twain" },
{ id: 385, quote: "It does not matter how slowly you go as long as you do not stop.", author: "Confucius" },
{ id: 386, quote: "Success usually comes to those who are too busy to be looking for it.", author: "Henry David Thoreau" },
{ id: 387, quote: "Don’t stop when you’re tired. Stop when you’re done.", author: "Unknown" },
{ id: 388, quote: "Wake up with determination. Go to bed with satisfaction.", author: "Unknown" },
{ id: 389, quote: "You are never too old to set another goal or to dream a new dream.", author: "C.S. Lewis" },
{ id: 390, quote: "Dream big and dare to fail.", author: "Norman Vaughan" },
{ id: 391, quote: "The best revenge is massive success.", author: "Frank Sinatra" },
{ id: 392, quote: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt" },
{ id: 393, quote: "Dream bigger. Do bigger.", author: "Unknown" },
{ id: 394, quote: "You miss 100% of the shots you don't take.", author: "Wayne Gretzky" },
{ id: 395, quote: "It always seems impossible until it's done.", author: "Nelson Mandela" },
{ id: 396, quote: "Success is not final, failure is not fatal: It is the courage to continue that counts.", author: "Winston Churchill" },
{ id: 397, quote: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
{ id: 398, quote: "The harder you work for something, the greater you’ll feel when you achieve it.", author: "Unknown" },
{ id: 399, quote: "Your limitation—it's only your imagination.", author: "Unknown" },
{ id: 400, quote: "Push yourself, because no one else is going to do it for you.", author: "Unknown" },
{ id: 401, quote: "Great things never come from comfort zones.", author: "Anonymous" },
{ id: 402, quote: "Dream it. Wish it. Do it.", author: "Unknown" },
{ id: 403, quote: "Success doesn’t just find you. You have to go out and get it.", author: "Unknown" },
{ id: 404, quote: "The harder you work, the luckier you get.", author: "Gary Player" },
{ id: 405, quote: "Dream it. Believe it. Achieve it.", author: "Unknown" },
{ id: 406, quote: "Success is what happens after you have survived all your mistakes.", author: "Anonymous" },
{ id: 407, quote: "The only limit to our realization of tomorrow is our doubts of today.", author: "Franklin D. Roosevelt" },
{ id: 408, quote: "Act as if what you do makes a difference. It does.", author: "William James" },
{ id: 409, quote: "Success is the sum of small efforts, repeated day in and day out.", author: "Robert Collier" },
{ id: 410, quote: "Don’t wait. The time will never be just right.", author: "Napoleon Hill" },
{ id: 411, quote: "Everything you’ve ever wanted is on the other side of fear.", author: "George Addair" },
{ id: 412, quote: "You are capable of more than you know.", author: "Gloria Steinem" },
{ id: 413, quote: "Do something today that your future self will thank you for.", author: "Unknown" },
{ id: 414, quote: "Success is walking from failure to failure with no loss of enthusiasm.", author: "Winston Churchill" },
{ id: 415, quote: "Hardships often prepare ordinary people for an extraordinary destiny.", author: "C.S. Lewis" },
{ id: 416, quote: "The best way to predict your future is to create it.", author: "Abraham Lincoln" },
{ id: 417, quote: "You don’t have to be great to start, but you have to start to be great.", author: "Zig Ziglar" },
{ id: 418, quote: "Success is not how high you have climbed, but how you make a positive difference to the world.", author: "Roy T. Bennett" },
{ id: 419, quote: "There are no shortcuts to any place worth going.", author: "Beverly Sills" },
{ id: 420, quote: "Success is the result of preparation, hard work, and learning from failure.", author: "Colin Powell" },
{ id: 421, quote: "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.", author: "Christian D. Larson" },
{ id: 422, quote: "Everything has beauty, but not everyone sees it.", author: "Confucius" },
{ id: 423, quote: "The secret to getting ahead is getting started.", author: "Mark Twain" },
{ id: 424, quote: "Life is 10% what happens to us and 90% how we react to it.", author: "Charles R. Swindoll" },
{ id: 425, quote: "There are no limits to what you can accomplish, except the limits you place on your own thinking.", author: "Brian Tracy" },
{ id: 426, quote: "Success is not in what you have, but who you are.", author: "Bo Bennett" },
{ id: 427, quote: "The road to success and the road to failure are almost exactly the same.", author: "Colin R. Davis" },
{ id: 428, quote: "The best revenge is massive success.", author: "Frank Sinatra" },
{ id: 429, quote: "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful.", author: "Albert Schweitzer" },
{ id: 430, quote: "Don’t be afraid to give up the good to go for the great.", author: "John D. Rockefeller" },
{ id: 431, quote: "If you can dream it, you can do it.", author: "Walt Disney" },
{ id: 432, quote: "You are never too old to set another goal or to dream a new dream.", author: "C.S. Lewis" },
{ id: 433, quote: "Don’t limit your challenges. Challenge your limits.", author: "Jerry Dunn" },
{ id: 434, quote: "The secret of getting ahead is getting started.", author: "Mark Twain" },
{ id: 435, quote: "It does not matter how slowly you go as long as you do not stop.", author: "Confucius" },
{ id: 436, quote: "Success usually comes to those who are too busy to be looking for it.", author: "Henry David Thoreau" },
{ id: 437, quote: "Don’t stop when you’re tired. Stop when you’re done.", author: "Unknown" },
{ id: 438, quote: "Wake up with determination. Go to bed with satisfaction.", author: "Unknown" },
{ id: 439, quote: "You are never too old to set another goal or to dream a new dream.", author: "C.S. Lewis" },
{ id: 440, quote: "Dream big and dare to fail.", author: "Norman Vaughan" },
{ id: 441, quote: "The best revenge is massive success.", author: "Frank Sinatra" },
{ id: 442, quote: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt" },
{ id: 443, quote: "Dream bigger. Do bigger.", author: "Unknown" },
{ id: 444, quote: "You miss 100% of the shots you don't take.", author: "Wayne Gretzky" },
{ id: 445, quote: "It always seems impossible until it's done.", author: "Nelson Mandela" },
{ id: 446, quote: "Success is not final, failure is not fatal: It is the courage to continue that counts.", author: "Winston Churchill" },
{ id: 447, quote: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
{ id: 448, quote: "The harder you work for something, the greater you’ll feel when you achieve it.", author: "Unknown" },
{ id: 449, quote: "Your limitation—it's only your imagination.", author: "Unknown" },
{ id: 450, quote: "Push yourself, because no one else is going to do it for you.", author: "Unknown" },
{ id: 451, quote: "Success doesn’t come from what you do occasionally, it comes from what you do consistently.", author: "Marie Forleo" },
{ id: 452, quote: "The key to success is to focus on goals, not obstacles.", author: "Unknown" },
{ id: 453, quote: "Success is the sum of small efforts, repeated day in and day out.", author: "Robert Collier" },
{ id: 454, quote: "Believe you can and you're halfway there.", author: "Theodore Roosevelt" },
{ id: 455, quote: "A dream becomes a goal when action is taken toward its achievement.", author: "Bo Bennett" },
{ id: 456, quote: "If you want to achieve greatness stop asking for permission.", author: "Unknown" },
{ id: 457, quote: "Success is not in what you have, but who you are.", author: "Bo Bennett" },
{ id: 458, quote: "Don’t wait. The time will never be just right.", author: "Napoleon Hill" },
{ id: 459, quote: "Success is not how high you have climbed, but how you make a positive difference to the world.", author: "Roy T. Bennett" },
{ id: 460, quote: "A year from now you may wish you had started today.", author: "Karen Lamb" },
{ id: 461, quote: "The best way to predict the future is to create it.", author: "Abraham Lincoln" },
{ id: 462, quote: "Success is not in what you have, but who you are.", author: "Bo Bennett" },
{ id: 463, quote: "Success is not final, failure is not fatal: It is the courage to continue that counts.", author: "Winston Churchill" },
{ id: 464, quote: "The road to success and the road to failure are almost exactly the same.", author: "Colin R. Davis" },
{ id: 465, quote: "Don’t stop when you’re tired. Stop when you’re done.", author: "Unknown" },
{ id: 466, quote: "The harder you work for something, the greater you’ll feel when you achieve it.", author: "Unknown" },
{ id: 467, quote: "Success is what happens after you have survived all your mistakes.", author: "Anonymous" },
{ id: 468, quote: "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful.", author: "Albert Schweitzer" },
{ id: 469, quote: "Success usually comes to those who are too busy to be looking for it.", author: "Henry David Thoreau" },
{ id: 470, quote: "The way to get started is to quit talking and begin doing.", author: "Walt Disney" },
{ id: 471, quote: "Don’t wait. The time will never be just right.", author: "Napoleon Hill" },
{ id: 472, quote: "You are never too old to set another goal or to dream a new dream.", author: "C.S. Lewis" },
{ id: 473, quote: "Success doesn’t come from what you do occasionally, it comes from what you do consistently.", author: "Marie Forleo" },
{ id: 474, quote: "Success is not how high you have climbed, but how you make a positive difference to the world.", author: "Roy T. Bennett" },
{ id: 475, quote: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
{ id: 476, quote: "Success is not final, failure is not fatal: It is the courage to continue that counts.", author: "Winston Churchill" },
{ id: 477, quote: "The harder you work, the luckier you get.", author: "Gary Player" },
{ id: 478, quote: "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful.", author: "Albert Schweitzer" },
{ id: 479, quote: "Dream big and dare to fail.", author: "Norman Vaughan" },
{ id: 480, quote: "Success is walking from failure to failure with no loss of enthusiasm.", author: "Winston Churchill" },
{ id: 481, quote: "The best revenge is massive success.", author: "Frank Sinatra" },
{ id: 482, quote: "You are capable of more than you know.", author: "Gloria Steinem" },
{ id: 483, quote: "Everything you’ve ever wanted is on the other side of fear.", author: "George Addair" },
{ id: 484, quote: "The key to success is to focus on goals, not obstacles.", author: "Unknown" },
{ id: 485, quote: "Success is the sum of small efforts, repeated day in and day out.", author: "Robert Collier" },
{ id: 486, quote: "Success is not in what you have, but who you are.", author: "Bo Bennett" },
{ id: 487, quote: "Success is not final, failure is not fatal: It is the courage to continue that counts.", author: "Winston Churchill" },
{ id: 488, quote: "The road to success and the road to failure are almost exactly the same.", author: "Colin R. Davis" },
{ id: 489, quote: "The harder you work for something, the greater you’ll feel when you achieve it.", author: "Unknown" },
{ id: 490, quote: "Success is what happens after you have survived all your mistakes.", author: "Anonymous" },
{ id: 491, quote: "Dream it. Wish it. Do it.", author: "Unknown" },
{ id: 492, quote: "Don’t wait for opportunity. Create it.", author: "Brian Tracy" },
{ id: 493, quote: "The best way to predict your future is to create it.", author: "Abraham Lincoln" },
{ id: 494, quote: "The only limit to our realization of tomorrow is our doubts of today.", author: "Franklin D. Roosevelt" },
{ id: 495, quote: "Hardships often prepare ordinary people for an extraordinary destiny.", author: "C.S. Lewis" },
{ id: 496, quote: "The best way to predict the future is to create it.", author: "Abraham Lincoln" },
{ id: 497, quote: "Act as if what you do makes a difference. It does.", author: "William James" },
{ id: 498, quote: "Success is the sum of small efforts, repeated day in and day out.", author: "Robert Collier" },
{ id: 499, quote: "Don’t wait. The time will never be just right.", author: "Napoleon Hill" },
{ id: 500, quote: "Everything you’ve ever wanted is on the other side of fear.", author: "George Addair" }
];

// Pagination middleware
app.get('/quotes', (req, res) => {
  const page = parseInt(req.query.page) || 1; // Default to first page
  const limit = parseInt(req.query.limit) || 10; // Default to 10 quotes per page
  const startIndex = (page - 1) * limit; // Calculate starting index
  const endIndex = page * limit; // Calculate ending index

  // Get paginated quotes
  const results = {};

  if (startIndex > 0) {
    results.previous = {
      page: page - 1,
      limit: limit,
    };
  }

  if (endIndex < quotes.length) {
    results.next = {
      page: page + 1,
      limit: limit,
    };
  }

  results.quotes = quotes.slice(startIndex, endIndex);
  res.json(results);
});

app.listen(port, () => {
  console.log(`Server is running on http://localhost:${port}`);
});